Repository prathimacode-hub/DS-ScriptsNook, pull requests merged in 2021-07, with the labels that each got.

#8 Adding ML algorithm- Linear Regression #5
  Machine Learning/Algorithms/Linear Regression/Images/lr1.jpg
  Machine Learning/Algorithms/Linear Regression/Images/lr2.jpg
  Machine Learning/Algorithms/Linear Regression/Images/lr3.jpg
  Machine Learning/Algorithms/Linear Regression/Images/lr4.jpg
  Machine Learning/Algorithms/Linear Regression/Images/lr5.jpg
  Machine Learning/Algorithms/Linear Regression/Images/lr6.jpg
  Machine Learning/Algorithms/Linear Regression/Images/lr7.jpg
  Machine Learning/Algorithms/Linear Regression/README.md
  Machine Learning/Algorithms/Linear Regression/linear_regression.ipynb
Labels: DCP21, 🟧 Level3

#15 Added Random Forest Classifier Algorithm
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf.png
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf2.png
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf3.png
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf4.png
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf5.png
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf6.png
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf7.png
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf8.png
  Machine Learning/Algorithms/Random Forest Classifier/Images/rf9.png
  Machine Learning/Algorithms/Random Forest Classifier/README.md
  Machine Learning/Algorithms/Random Forest Classifier/Random_Forest_Classifier.ipynb
Labels: DCP21, 🟨 Level2

#18 Add files of Text Summarization using NLP
  Natural Language Processing/Algorithms/README.md
  Natural Language Processing/Algorithms/Text Summarization/Images/1.png.jpg
  Natural Language Processing/Algorithms/Text Summarization/Images/2.jpg
  Natural Language Processing/Algorithms/Text Summarization/Images/3.jpg
  Natural Language Processing/Algorithms/Text Summarization/Images/4.png
  Natural Language Processing/Algorithms/Text Summarization/Images/5.jpg
  Natural Language Processing/Algorithms/Text Summarization/Images/6.png
  Natural Language Processing/Algorithms/Text Summarization/README.md
  Natural Language Processing/Algorithms/Text Summarization/text summarization.ipynb
Labels: DCP21, 🟧 Level3

#20 Random Forest Regressor Algorithm.#13
  Machine Learning/Algorithms/Random Forest Regressor/Images/rrr1.jpg
  Machine Learning/Algorithms/Random Forest Regressor/Images/rrr2.jpg
  Machine Learning/Algorithms/Random Forest Regressor/Images/rrr3.jpg
  Machine Learning/Algorithms/Random Forest Regressor/Images/rrr4.jpg
  Machine Learning/Algorithms/Random Forest Regressor/Images/rrr5.jpg
  Machine Learning/Algorithms/Random Forest Regressor/Images/rrr6.jpg
  Machine Learning/Algorithms/Random Forest Regressor/Images/rrr7.jpg
  Machine Learning/Algorithms/Random Forest Regressor/Images/rrr8.jpg
  Machine Learning/Algorithms/Random Forest Regressor/README.md
  Machine Learning/Algorithms/Random Forest Regressor/random_forest_regressor.ipynb
Labels: DCP21, 🟧 Level3

#19 NLP based Chatbot
  Natural Language Processing/Tutorials/NLP Based Chatbot/Dataset/RickAndMortyScripts.csv
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/Arguments.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/Data Processing.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/Data Vis1.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/Mounting.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/Test.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/Train.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/Transformer.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/ex1.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/ex2.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/Images/libraries.jpeg
  Natural Language Processing/Tutorials/NLP Based Chatbot/README.md
  Natural Language Processing/Tutorials/NLP Based Chatbot/discord_bot.ipynb
  Natural Language Processing/Tutorials/NLP Based Chatbot/kaggleJSON/kaggle.json
Labels: DCP21, 🟧 Level3

#24 Word Tokenization Techniques in NLP
  Natural Language Processing/Algorithms/Word Tokenization Techniques/README.md
  Natural Language Processing/Algorithms/Word Tokenization Techniques/Word_tokenization_techniques_in_NLP.ipynb
Labels: DCP21, To Do, 🟧 Level3

#26 Decision Tree Classifier Algorithm #21
  Machine Learning/Algorithms/Decision Tree Classifier/Images/dtc1.jpg
  Machine Learning/Algorithms/Decision Tree Classifier/Images/dtc2.jpg
  Machine Learning/Algorithms/Decision Tree Classifier/Images/dtc3.jpg
  Machine Learning/Algorithms/Decision Tree Classifier/Images/dtc4.jpg
  Machine Learning/Algorithms/Decision Tree Classifier/Images/dtc5.jpg
  Machine Learning/Algorithms/Decision Tree Classifier/Images/dtc6.jpg
  Machine Learning/Algorithms/Decision Tree Classifier/README.md
  Machine Learning/Algorithms/Decision Tree Classifier/decision_tree_classifier.ipynb
Labels: DCP21, To Do, 🟧 Level3

#25 YouTube Comments Analyser
  Machine Learning/Tutorials/Youtube Comments Classifier/Datasets/Youtube01-Psy.csv
  Machine Learning/Tutorials/Youtube Comments Classifier/Datasets/Youtube02-KatyPerry.csv
  Machine Learning/Tutorials/Youtube Comments Classifier/Datasets/Youtube03-LMFAO.csv
  Machine Learning/Tutorials/Youtube Comments Classifier/Datasets/Youtube04-Eminem.csv
  Machine Learning/Tutorials/Youtube Comments Classifier/Datasets/Youtube05-Shakira.csv
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Accuracy.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/After Processing.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Before Processing.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Data Preparation 1.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Data Preparation 2.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Drive Mounting.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Importing and concatinating the Dataset.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Setting up Variables.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Testing.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Images/Training and Evaluation.jpeg
  Machine Learning/Tutorials/Youtube Comments Classifier/Model/youtube_comments_classifier.ipynb
  Machine Learning/Tutorials/Youtube Comments Classifier/README.md
Labels: DCP21, To Do, 🟧 Level3

#29 KNN Algorithm #28
  Machine Learning/Algorithms/KNN Classifier/Images/knn1.jpg
  Machine Learning/Algorithms/KNN Classifier/Images/knn2.jpg
  Machine Learning/Algorithms/KNN Classifier/Images/knn3.jpg
  Machine Learning/Algorithms/KNN Classifier/Images/knn4.jpg
  Machine Learning/Algorithms/KNN Classifier/Images/knn5.jpg
  Machine Learning/Algorithms/KNN Classifier/Images/knn6.jpg
  Machine Learning/Algorithms/KNN Classifier/README.md
  Machine Learning/Algorithms/KNN Classifier/knn_classifier.ipynb
Labels: DCP21, To Do, 🟧 Level3

#115 Logistic Regression #114
  Machine Learning/Algorithms/Logistic Regression/Images/lr1.jpg
  Machine Learning/Algorithms/Logistic Regression/Images/lr2.jpg
  Machine Learning/Algorithms/Logistic Regression/Images/lr3.jpg
  Machine Learning/Algorithms/Logistic Regression/Images/lr4.jpg
  Machine Learning/Algorithms/Logistic Regression/Images/lr5.jpg
  Machine Learning/Algorithms/Logistic Regression/Images/lr6.jpg
  Machine Learning/Algorithms/Logistic Regression/Images/lr7.jpg
  Machine Learning/Algorithms/Logistic Regression/Images/lr8.jpg
  Machine Learning/Algorithms/Logistic Regression/README.md
  Machine Learning/Algorithms/Logistic Regression/logistic_regression.ipynb
Labels: DCP21, To Do, 🟧 Level3
